-	import { useEffect, useState } from "react";
-	
-	function App1() {
-	  useEffect(() => {
-	    console.log('connect')
-	
-	    // return () => console.log('disconnect')
-	
-	  }, [])
-	  return (
-	    <>
-	      <p>Connect</p>
-	    </>
-	  )
-	}
-	
-	export default function App() {
-	  const [a, setA] = useState(true);
-	  useEffect(() => {
-	    const btn = document.querySelector('button');
-	    btn.addEventListener('click', () => console.log('click'))
-	    btn.addEventListener('click', () => console.log('click'))
-	  }, [])
-	
-	  return (
-	    <>
-	      <button onClick={() => setA(!a)}>Click</button>
-	      {a && <App1 />}
-	    </>
-	  )
-	}
